name: semogaberkah
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter
  
  google_generative_ai: ^0.4.7 
  intl: ^0.20.2
  supabase_flutter: ^2.10.3
  flutter_local_notifications: ^17.2.1
  
  # --- PERBAIKAN VERSIONING (MENGATASI BUILD ERROR) ---
  # Mengatasi error Registrar/Embedding V1 (memaksa versi modern)
  timezone: ^0.9.4
  flutter_timezone: ^5.0.1 
  geolocator: ^12.0.0 
  # ----------------------------------------------------
  
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  http: ^1.2.1
  geocoding: ^3.0.0
  google_fonts: ^6.2.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  rive: ^0.13.20 # Untuk Animasi Login Page
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0 # Biarkan ini ada untuk saat ini

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png" 
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/animation/ # Untuk Riv